gender <- factor(c("M", "F", "M", "F", "F", "F", "F", "F", "F", "M", "M", "F", "M", "M", "F", "F"))
ethnicity <- factor (c("Asian", "Asian", "White", "White", "Hispanic", "White", "Hispanic", "Asian", "Asian", "White", "Hispanic", "Asian", "Asian", "Latin American", "White", "White"))
age <- c(29, 21, 27, 23, 21, 22, 24, 31, 24, 24, 24, 23, 24, 30, 23, 26)
lastname <- factor(c("H", "H", "R", "M", "L", "T", "F", "L", "J", "M", "L", "R", "A", "R", "S", "R"))
height <- c(72, 66, 69, 65, 62, 65, 59, 63, 64, 72, 69.5, 63, 65, 63, 68, 63)
datasummary <- data.frame(gender, ethnicity, age, lastname, height)
summary(datasummary)
tiff(filename = "fig1", res = 100)
plot(height ~ gender, data = datasummary)
dev.off()
tiff(filename = "fig2", res = 100)
plot(height ~ ethnicity, data = datasummary)
dev.off()
tiff(filename = "fig3", res = 100)
plot(height ~ lastname, data = datasummary)
dev.off()
tiff(filename = "fig4", res = 100)
plot(height ~ age, data = datasummary)
dev.off()
t.test(height[gender == "F"], height[gender == "M"])
t.test(height[ethnicity == "White"], height[ethnicity == "Asian"])
t.test(height[ethnicity == "White"], height[ethnicity == "Hispanic"])
t.test(height[ethnicity == "White"], height[ethnicity == "Latin American"])
